name: Push to Git Hub repo
variables:
  repo: $(REPO_NAME_TEST)
  pat: $(GITHUB_PAT)
  username: $(USERNAME)
  email: $(EMAIL)
stages:
  - stage: running_git_commands
    displayName: running_git_commands
    jobs:
      - job: initiate
        displayName: initiate
        continueOnError: false
        steps:
        - bash: |
            git clone https://github.com/scw-digital-intelligence/product_cat_test.git
            git config --global user.name scw-digital-intelligence
            git checkout master
            git add .
            git commit -m "Latest version of the catalogue"
            git push https://%$$(pat)%@github.com/scw-digital-intelligence/product_cat_test.git
          displayName: 'Copy to Github'
          condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')