name: Push to Git Hub repo
variables:
  repo: $(REPO_NAME_TEST)
  pat: $(GITHUB_PAT)
  username: $(USERNAME)
  email: $(EMAIL)
stages:
  - stage: running_git_commands
    displayName: running_git_commands
    jobs:
      - job: initiate
        displayName: initiate
        continueOnError: false
        steps:
        - script: |
            git clone https://github.com/$(username)/$(repo).git
            git config --global user.email $(email)
            git config --global user.name $(username)
            git checkout master
            git add .
            git commit -m "Latest version of the catalogue"
            git push https://UserName:UserPassword@github.com/xxx/TestUpload.git master
          displayName: 'Copy to Github'
          condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')