name: Push to Git Hub repo
variables:
  repo: $(REPO_NAME_TEST)
  pat: $(GITHUB_PAT)
  username: $(USERNAME)
stages:
  - stage: running_git_commands
    displayName: running_git_commands
    jobs:
      - job: initiate
        displayName: initiate
        continueOnError: false
        steps:
        - bash: |
            git config --global user.name $(username)
            git config --global github.token $(pat)
            git clone https://github.com/scw-digital-intelligence/product_cat_test.git
            git checkout master
            git add .
            git commit -m "abc"
            git push https://%$(pat)%@github.com/scw-digital-intelligence/product_cat_test.git
          displayName: 'Copy to Github'
          condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')